/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RsrvabakahrxhaIndexRouteImport } from './routes/rsrvabakahrxha/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as RsrvabakahrxhaLoginRouteImport } from './routes/rsrvabakahrxha/login'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RsrvabakahrxhaIndexRoute = RsrvabakahrxhaIndexRouteImport.update({
  id: '/rsrvabakahrxha/',
  path: '/rsrvabakahrxha/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const RsrvabakahrxhaLoginRoute = RsrvabakahrxhaLoginRouteImport.update({
  id: '/rsrvabakahrxha/login',
  path: '/rsrvabakahrxha/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/rsrvabakahrxha/login': typeof RsrvabakahrxhaLoginRoute
  '/projects/': typeof ProjectsIndexRoute
  '/rsrvabakahrxha/': typeof RsrvabakahrxhaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/rsrvabakahrxha/login': typeof RsrvabakahrxhaLoginRoute
  '/projects': typeof ProjectsIndexRoute
  '/rsrvabakahrxha': typeof RsrvabakahrxhaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/rsrvabakahrxha/login': typeof RsrvabakahrxhaLoginRoute
  '/projects/': typeof ProjectsIndexRoute
  '/rsrvabakahrxha/': typeof RsrvabakahrxhaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/projects/$slug'
    | '/rsrvabakahrxha/login'
    | '/projects/'
    | '/rsrvabakahrxha/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/projects/$slug'
    | '/rsrvabakahrxha/login'
    | '/projects'
    | '/rsrvabakahrxha'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/projects/$slug'
    | '/rsrvabakahrxha/login'
    | '/projects/'
    | '/rsrvabakahrxha/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  RsrvabakahrxhaLoginRoute: typeof RsrvabakahrxhaLoginRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RsrvabakahrxhaIndexRoute: typeof RsrvabakahrxhaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsrvabakahrxha/': {
      id: '/rsrvabakahrxha/'
      path: '/rsrvabakahrxha'
      fullPath: '/rsrvabakahrxha/'
      preLoaderRoute: typeof RsrvabakahrxhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsrvabakahrxha/login': {
      id: '/rsrvabakahrxha/login'
      path: '/rsrvabakahrxha/login'
      fullPath: '/rsrvabakahrxha/login'
      preLoaderRoute: typeof RsrvabakahrxhaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  RsrvabakahrxhaLoginRoute: RsrvabakahrxhaLoginRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RsrvabakahrxhaIndexRoute: RsrvabakahrxhaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
